version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bash -c "gunicorn backend.asgi:application --bind 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker" 
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  redis:
    image: redis:6
    container_name: local_redis
    ports:
      - "6379:6379"
  frontend:
    build: 
      dockerfile: Dockerfile
      context: frontend
    command: serve -s build
    expose:
      - 3000
    env_file:
      - .env
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "55001:55001"
      - "55002:55002"
    depends_on:
      web:
        condition: service_started
      frontend:
        condition: service_started

volumes:
  postgres_data: