version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bash -x "cd backend && gunicorn backend.wsgi:application --bind 0.0.0.0:8000" 
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  redis:
    image: redis:6
    container_name: local_redis
    ports:
      - "6379:6379"
  frontend:
    build: 
      dockerfile: Dockerfile
      context: ./frontend
    container_name: node_front
    command: bash -c "cp -r /usr/src/cache/node_modules/. /node_modules/ && npm start"
    volumes:
      - ./frontend:/node
    ports:
      - "3000:3000"
    env_file:
      - ./.env

volumes:
  postgres_data: