name: Deploy to Oracle Cloud

on:
  push:
    branches:
      - prod

env:
  ORACLE_REGISTRY_EMAIL: ${{ secrets.ORACLE_REGISTRY_EMAIL }}
  ORACLE_REGISTRY_PASSWORD: ${{ secrets.ORACLE_REGISTRY_PASSWORD }}
  DOCKER_IMAGE_TAG_1: web
  DOCKER_IMAGE_TAG_2: frontend
  OCI_REGION: ap-osaka-1
  OCI_COMPARTMENT_ID: ocid1.compartment.oc1..aaaaaaaaug6ru674p6lvjwlhugxkezanhvkmzemn2zszlsk4pomwipbkxpma
  OCI_AVAILABILITY_DOMAIN: AD-1
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/django_react:${{ env.DOCKER_IMAGE_TAG_1 }}
          ${{ secrets.DOCKERHUB_USERNAME }}/django_react:${{ env.DOCKER_IMAGE_TAG_2 }}

    - name: Login to Oracle Cloud
      uses: docker/login-action@v2
      with:
        registry: ${{ env.OCI_REGION }}.ocir.io
        username: axnlgidkiqam/abushkasunntovsss@gmail.com
        password: tzkJ5;6i:f+Jjds{sw2>
    
    - name: Push to Oracle Cloud
      run: |
        docker tag ${{ env.DOCKERHUB_USERNAME }}/django_react:web ${{ env.OCI_REGION }}.ocir.io/aaaaaaaaz43obwqdygm47zpwhr4c3sfvumypx4j4wfonbu4kx6v73k6dznjq/react_django:web
        docker push ${{ env.OCI_REGION }}.ocir.io/aaaaaaaaz43obwqdygm47zpwhr4c3sfvumypx4j4wfonbu4kx6v73k6dznjq/react_django
